baseURL = "https://ippee.github.io/dhak_docs"
languageCode = "en-us"
title = "Dhak"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  # google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Dhak is a CUI/GUI password manager without keeping passwords, in Dart/Flutter.'
  homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "A CUI/GUI password manager without keeping passwords, in Dart/Flutter."
    meta_og_title = "Dhak"
    meta_og_type = "website"
    meta_og_url = "https://ippee.github.io/dhak_docs"
    meta_og_image = ""
    meta_og_description = "A CUI/GUI password manager without keeping passwords, in Dart/Flutter."
    # meta_twitter_card = "summary"
    # meta_twitter_site = "@zerostaticio"
    # meta_twitter_creator = "@zerostaticio"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
